### PR TITLE
Final version review

### PR DESCRIPTION
**Pull request by rodneyosodo**
Signed-off-by: 0x6f736f646f <blackd0t@protonmail.com>

# Pull Request Template

* **Please check if the PR fulfils these requirements**
- [x] The commit message follows our guidelines
- [x] Docs have been added / updated (for bug fixes / features)

## Description

New changes to the PCB
- Moving from esp32 SoC to esp32 IC
- Adding wifi amplifier
- Changing antenna connectors
- Removing extra flash memory

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## What is the current behavior?** (You can also link to an open issue here)
No open issues

## What is the new behaviour (if this is a feature change)?
Wifi amplification

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rodneyosodo** [comment]
Resolves #1

**Review by WashingtonKK — COMMENTED** [review]
Looks good from this end.

**Comment by rodneyosodo** [comment]
Resolves #4 
Resolves #5 
Resolves #6 
Resolves #7 
Resolves #8 
Resolves #9 
Resolves #10 
Resolves #11 
Resolves #12 
Resolves #13

**Comment by rodneyosodo** [comment]
@SammyOina

**Comment by rodneyosodo** [comment]
@1998-felix

**Comment by rodneyosodo** [comment]
@Mike-Kimani

**Review by ianmuchyri — APPROVED** [review]

**Review by SammyOina — APPROVED** [review]

**Review by felixgateru — APPROVED** [review]
Just a typo on camera. So far looks good

**Pull request merged**
